#!/bin/bash -ex

source script/lib.sh

alltargets | while read target; do
    script/build ${target}
    timeout --preserve-status --signal=INT 10s \
        go-fuzz -bin=$(bin_file ${target}) -workdir=$(local_path ${target})
done
